### ISSUE TITLE
Feature request: clear input

### ISSUE THREAD

**Issue by Keko-94** [rodrigopaco1986/simple-daterange-picker#3]
Hey

Thanks for your package.

It would be awesome if we can clear the filter with a little cross at the end of the input :

![search-input-chrome](https://github.com/rodrigopaco1986/simple-daterange-picker/assets/62820283/1fcbea6c-ac4e-4183-bed2-0f8160b69408)

**Comment by rodrigopaco1986** [comment]
Added that feature. Commit 7b37308491b96c0bb8a5f62561445c8b5db37725
