### ISSUE TITLE
Can't set empty value to show all

### ISSUE THREAD

**Issue by whitespacecode** [rodrigopaco1986/simple-daterange-picker#6]
How can we default to showing all the results ?
In the readme you state: If no value is passed, TODAY value is set as default.

**Comment by yastrebf** [comment]
Yes. Show 'ALL' option needed

**Comment by rodrigopaco1986** [comment]
Coming soon that new option

**Comment by whitespacecode** [comment]
@yastrebf i found this package to work very good as well: https://github.com/idezdigital/nova-date-range-filter

**Comment by rodrigopaco1986** [comment]
@whitespacecode @yastrebf 
Please check new release which fix this: https://github.com/rodrigopaco1986/simple-daterange-picker/releases/tag/0.0.8
