### ISSUE TITLE
How  to filter on 2 date fields of a  table ?

### ISSUE THREAD

**Issue by sergeynilov** [rodrigopaco1986/simple-daterange-picker#8]
Thanks for your work and this usefull plugin!

I implemented this pluging("rpj/daterangepicker": "^0.0.8") in  Laravel 10 / nova 4.27 app  for products.published_at field and wonder if there is a way to filter on 2 date fields of a table :

```
CREATE TABLE `discounts` (
  `id` tinyint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  ...
  `active_from` date DEFAULT NULL,
  `active_till` date DEFAULT NULL,

```
?

**Comment by rodrigopaco1986** [comment]
hello @LTKort
It's not implemented yet. I'll add it soon in the next release (y)

**Comment by sergeynilov** [comment]
@stefvanesch  with 4 datepickers on the form ? Do you mean this ?

**Comment by rodrigopaco1986** [comment]
@stefvanesch please update to 0.0.9 version, you should be able to pass an array with two fields to filter, but you can still pass a single string as default:

```
(new \Rpj\Daterangepicker\Daterangepicker(['active_from', 'active_till']),
```
